INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, GENDER, EMAIL) VALUES (1, 'GANDALF', 'GREY', 'MALE', 'gandalf@gmail.com');
INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, GENDER, EMAIL) VALUES (2, 'ARWEN', 'EVENSTAR', 'FEMALE', 'arwen@gmail.com');
INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, GENDER, EMAIL) VALUES (3, 'FRODO', 'BAGGINS', 'MALE', 'frodo@gmail.com');
INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, GENDER, EMAIL) VALUES (4, 'MERRY', 'BRANDYBUCK', 'MALE', 'merry@gmail.com');
INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, GENDER, EMAIL) VALUES (5, 'SAMWISE', 'GAMGEE', 'MALE', 'samwise@gmail.com');
INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, GENDER, EMAIL) VALUES (6, 'PIPPIN', 'TOOK', 'MALE', 'pippin@gmail.com');

